export {default as FormRegisterUser} from './form'
export {default as ButtonSubmit} from './buttonSubmit'
export {default as HeaderRegisterForm} from './header'
export {default as InputLabel} from './input'
export {default as SelectPermission} from './selectPermission'
export {default as SwitchEnableUser} from './switch'
export {default as UploadUserPhoto} from './upload'
export {default as DateEntry} from './datePicker'